/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Sushi(props) {
  const { nodes, materials } = useGLTF('./sushi.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.099, 4.754, 4.855]} scale={0.496}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3.geometry}
          material={materials['Material.003']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plate.geometry}
        material={materials['Material.004']}
        position={[-2.065, 0.489, 1.33]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[-0.294, 4.412, 1.411]}
        scale={[0.959, 0.959, 1.252]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[-0.294, 4.412, 1.101]}
        scale={[0.959, 0.959, 1.27]}
      />
    </group>
  )
}

useGLTF.preload('./sushi.gltf')
